2020-06-22 13:17:22,145 - __main__ - WARNING - warning
2020-06-22 13:17:22,145 - __main__ - CRITICAL - fatal
2020-06-22 13:17:22,145 - __main__ - CRITICAL - critical
2020-06-22 13:17:22,145 - __main__ - ERROR - error
2020-06-22 13:17:22,146 - __main__ - ERROR - Failed to open sklearn.txt from logger.exception
Traceback (most recent call last):
  File "D:/MySpace/Python/bulitin/s_logging.py", line 49, in <module>
    open("../data/mysql.inis", "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/mysql.inis'
2020-06-22 13:18:33,720 - __main__ - WARNING - warning
2020-06-22 13:18:33,721 - __main__ - CRITICAL - fatal
2020-06-22 13:18:33,721 - __main__ - CRITICAL - critical
2020-06-22 13:18:33,721 - __main__ - ERROR - error
