2020-06-22 13:10:16,743 - __main__ - WARNING - warning
2020-06-22 13:10:16,749 - __main__ - CRITICAL - fatal
2020-06-22 13:10:16,749 - __main__ - CRITICAL - critical
2020-06-22 13:10:16,749 - __main__ - ERROR - error
2020-06-22 13:10:18,568 - __main__ - WARNING - warning
2020-06-22 13:10:18,568 - __main__ - CRITICAL - fatal
2020-06-22 13:10:18,568 - __main__ - CRITICAL - critical
2020-06-22 13:10:18,568 - __main__ - ERROR - error
2020-06-22 13:15:36,285 - __main__ - WARNING - warning
2020-06-22 13:15:36,286 - __main__ - CRITICAL - fatal
2020-06-22 13:15:36,286 - __main__ - CRITICAL - critical
2020-06-22 13:15:36,286 - __main__ - ERROR - error
2020-06-22 13:15:36,286 - __main__ - ERROR - Failed to open sklearn.txt from logger.exception
Traceback (most recent call last):
  File "D:/MySpace/Python/bulitin/s_logging.py", line 49, in <module>
    open("../data/no_file.txt", "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/no_file.txt'
